services:
  - type: web
    name: sisa-ai
    env: python310
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: OPENAI_API_KEY
        scope: build
